### ISSUE TITLE
Elasticsearch logging container crashing due to max_map_count

### ISSUE THREAD

**Issue by joelchrist** [wrsinc/kubernetes-efk-gcp#1]
![image](https://user-images.githubusercontent.com/11542720/36383183-ad3b5320-158b-11e8-9c7d-a84ced7cafd9.png)

**Comment by alexcurtin** [comment]
@joelchrist ```This section utilizes an init-container to run the command sysctl -w vm.max_map_count=262144 on the kubernetes nodes themselves, which is required by Elasticsearch in versions > 4.0.

``` the readme covers this issue, does it still happen for you?
